"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-)_e6c!4z6v=b9ln&2+9yh2ww$4ka9b+5m01v+$%o!bc#=qz6!b'

DEBUG = True
ALLOWED_HOSTS = []


# 🌱 Jazzmin UI Customization
JAZZMIN_SETTINGS = {
    "site_title": "AgriSmart Admin",
    "site_header": "🌱 AgriSmart Dashboard",
    "site_brand": "AgriSmart",
    "welcome_sign": "Welcome back, Admin 👨‍💼",
    "copyright": "AgriSmart Community Forum",
    "show_ui_builder": True,  # Enables live theme editor in admin

    # Icons for apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "myapp.Message": "fas fa-comments",  # Forum messages
    },

    # Sidebar menu order
    "order_with_respect_to": ["auth", "myapp"],

    # Custom links
    "custom_links": {
        "myapp": [{
            "name": "Community Forum",
            "url": "/community_forum/",
            "icon": "fas fa-comments",
            "permissions": ["auth.view_user"]
        }]
    },
}

# 🌱 Jazzmin UI Colors & Theme (Green + Orange)
JAZZMIN_UI_TWEAKS = {
    "theme": "minty",       # Fresh green base theme
    "dark_mode_theme": "darkly",

    # Navbar & Sidebar
    "navbar": "navbar-dark bg-success",        # Dark green navbar
    "sidebar": "sidebar-dark-success",         # Green sidebar
    "brand_colour": "navbar-success",          # Brand = green
    "accent": "accent-warning",                # 🔶 Orange accents
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,

    # Buttons (Green primary + Orange secondary)
    "button_classes": {
        "primary": "btn-success",          # ✅ Green main buttons
        "secondary": "btn-warning",        # 🔶 Orange buttons
        "info": "btn-info",
        "warning": "btn-outline-warning",  # Outlined orange
        "danger": "btn-danger",
    },

    # Sidebar tweaks
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_flat_style": False,

    # Login page
    "login_logo": None,  # Add custom logo from /static/ if you want
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "welcome_sign": "🌱 Welcome to AgriSmart Admin",
    "copyright": "© 2025 AgriSmart Platform",
}


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ✅ Optional: custom templates dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ✅ Use ASGI instead of WSGI
ASGI_APPLICATION = 'myproject.asgi.application'

# Channels config (using in-memory layer for dev)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# === EMAIL CONFIGURATION ===

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "climateapp02@gmail.com"       # replace this
EMAIL_HOST_PASSWORD = "ibmi eojb sbrh cfvg"      # replace this
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
