# Generated by Django 5.1.6 on 2025-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
