# Generated by Django 5.2.7 on 2025-10-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_chatmessage_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
